GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Adi",
    "email": "adi5@adi.com",
    "password": "123456",
    "confPassword": "123456",
    "ktp" : 287346387546,
    "alamat" : "jakarta",
    "phone" : "087365472283"

}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "jodi",
    "email": "adi234@adi.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/users/add
Content-Type: application/json

{
    "name": "Adi",
    "email": "adi@adi.com",
    "password": "123456"
}

###
DELETE  http://localhost:5000/users/5