GET http://localhost:5000/users

###
POST http://localhost:5000/users

Content-Type: application/json

{
    "name": "Adi",
    "email": "adi@adi.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/users/add

Content-Type: application/json

{
    "name": "Adi",
    "email": "adi@adi.com",
    "password": "123456"
}